;+
; NAME:
; ccldas_file_close
;
; PURPOSE:
; Closes an hdf5 file generated by the CCLDAS database query system.
;
; CALLING SEQUENCE:
; ccldas_file_close, file_id 
;
; INPUTS:
; file_id: An hdf5 file reference generated by ccldas_file_open.
;
; OUTPUTS:
; None
;
; MODIFICATION HISTORY:
; Written August 2012 by Spenser Burrows
;-


pro ccldas_file_close,file_id 
  H5F_CLOSE,file_id
END